#!/bin/bash

# populate Drones
declare -a Drones=()
while read line; do Drones=("${Drones[@]}" "$line"); done < drones

# How Many Caspers instances
for i in "${Drones[@]}"
do
   
#   echo "#############"
#   echo "Drone Health on $i"
#   ssh -t $i iostat
#   printf "\n"
#   ssh -t $i mpstat
#   ssh $i "drone_health=\$(mpstat); echo \$drone_health"
#   printf "\n"
#   ssh -t $i free -hm
#   ssh $i "drone_health=\$(free -hm); echo \$drone_health"
#   printf "\n"
#   ssh -t $i vmstat --unit m
#ssh $i "drone_health=\$(vmstat --unit m); echo \$drone_health"


   printf "\n"
   printf "\n"
   printf "\n"
   echo "Show how many email accounts used"
   cat /usr/local/bin/parties/meteor-agent-stresstest/accounts | wc -l 
   printf "\n"
   printf "\n"
   ssh $i "drone_cpu=\$(mpstat -P ALL); echo \drone_cpu"
   echo "####START####"
   echo "Show how many Immortal Casper(s) are running on $i"
   ssh $i "imm_run=\$(ps aux | grep -v grep | grep 'immortal' | wc -l); echo \$imm_run"
   echo "#############"
   echo "Show Immortal Casper(s) information on $i"
#   ps aux | head -1
#   ssh $i ps aux | grep -v grep | grep 'immortal'
   echo "#############"
   echo "Show how many tests have run on $i"
   ssh $i "imm_test=\$(cat count.txt | wc -l); echo \$imm_test"
#   ssh $i "imm_test=\$(cat count.txt | wc -l); echo \$imm_test" 
#   echo "#############"   

# Docker Information

   echo "Show how many Dockerized Casper(s) are actively running on $i"  
   ssh $i "var=\$(docker ps -q | wc -l); echo \$var"
#   echo "#############"
#   echo "Show how many Dockerized Casper(s) are zombies on $i"
#   echo "#############"
#   ssh $i "var=\$(docker ps -a ); echo \$var"
##   ssh $i "var=\$(docker top `docker ps -q`); echo \$var"
   printf "\n"
   echo "Show Docker Service Status on $i"
   ssh $i "var=\$(systemctl -l status docker | grep Active); echo  \$var"
   echo "#####END#####"
   printf "\n"
   printf "\n"
   printf "\n"
done
